# Generated by Django 5.1.4 on 2024-12-28 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditUnionBalance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("msisdn", models.IntegerField(primary_key=True, serialize=False)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                        ],
                        max_length=10,
                    ),
                ),
                ("request_date", models.DateField(auto_now_add=True)),
                (
                    "amount_requested",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "member_msisdn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KYCDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("id_type", models.CharField(blank=True, max_length=20, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "member_msisdn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "member_msisdn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApprovedLoan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount_of_loan",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("interest", models.DecimalField(decimal_places=2, max_digits=10)),
                ("end_of_loan_date", models.DateField()),
                (
                    "monthly_deduction",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount_left", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "member_msisdn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberBalance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "member_msisdn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.member"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("SAVINGS_WITHDRAWAL", "Savings Withdrawal"),
                            ("LOAN_REPAYMENT", "Loan Repayment"),
                            ("LOAN_WITHDRAWAL", "Loan Withdrawal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "member_msisdn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.member"
                    ),
                ),
            ],
        ),
    ]
