# Generated by Django 5.1.4 on 2024-12-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_loanrequest_loan_purpose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvedloan",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="MemberBalance",
        ),
    ]
