# Generated by Django 5.1.4 on 2024-12-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_approvedloan_status_delete_memberbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanrequest",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
