# Generated by Django 5.1.4 on 2024-12-30 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_loanrequest_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvedloan",
            name="loan_request_id",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.loanrequest",
            ),
            preserve_default=False,
        ),
    ]
