# Generated by Django 5.1.4 on 2024-12-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_approvedloan_loan_request_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approvedloan",
            name="loan_request_id",
        ),
    ]
