# Generated by Django 5.1.4 on 2025-01-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_approvedloan_loan_request_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kycdetails",
            name="id_type",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("SAVINGS WITHDRAWAL", "Savings Withdrawal"),
                    ("LOAN PAYMENT", "Loan payment"),
                    ("LOAN WITHDRAWAL", "Loan Withdrawal"),
                ],
                max_length=20,
            ),
        ),
    ]
