# Generated by Django 5.1.4 on 2025-01-01 18:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_transaction_date_transaction_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="time",
            field=models.TimeField(),
        ),
    ]
