# Generated by Django 5.1.4 on 2025-01-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_transaction_created_alter_transaction_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanrequest",
            name="request_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="loanrequest",
            name="request_time",
            field=models.TimeField(),
        ),
    ]
