# Generated by Django 5.1.4 on 2025-01-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_loanrequest_request_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="interest",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
    ]
