# Generated by Django 5.1.4 on 2025-01-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_contribution_interest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="deleted",
        ),
    ]
