# Generated by Django 5.1.4 on 2025-01-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_remove_member_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditunionbalance",
            name="name",
            field=models.CharField(default="The one", max_length=50),
            preserve_default=False,
        ),
    ]
