# Generated by Django 5.1.4 on 2025-01-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_approvedloan_user_id_contribution_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="msisdn",
            field=models.CharField(
                max_length=15, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
