# Generated by Django 5.1.4 on 2025-01-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_alter_member_msisdn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditunionbalance",
            name="name",
        ),
    ]
