# Generated by Django 5.1.4 on 2025-01-13 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_remove_loanrequest_request_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="time",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
