# Generated by Django 5.1.4 on 2025-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0024_transaction_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycdetails",
            name="name",
            field=models.CharField(default="name", max_length=150),
            preserve_default=False,
        ),
    ]
