# Generated by Django 5.1.4 on 2025-01-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_kycdetails_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kycdetails",
            old_name="last_name",
            new_name="other_names",
        ),
        migrations.RenameField(
            model_name="kycdetails",
            old_name="first_name",
            new_name="surname",
        ),
        migrations.AlterField(
            model_name="kycdetails",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
